# Ansible playbook for OpenBSD host setup
---
- hosts: vpn_hosts

  remote_user: root

  tasks:

  ##### System-wide preparations

  - name: Create your local user copy
    become: yes
    user:
      name: "{{ lookup('env', 'USER') }}"
      groups: wheel
      shell: /bin/sh
      state: present

  - name: Set authorized key took from file
    become: yes
    authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    with_items:
      - "{{ ansible_user_id }}"
      - "{{ lookup('env', 'USER') }}"

  # - name: Restrict root ssh login
  #   lineinfile:
  #     path: /etc/ssh/sshd_config
  #     owner: root
  #     group: wheel
  #     mode: 0640
  #     insertafter: '#PermitRootLogin yes'
  #     line: 'PermitRootLogin no'
  
  - name: Restrict ssh password auth
    lineinfile:
      path: /etc/ssh/sshd_config
      owner: root
      group: wheel
      mode: 0640
      insertafter: '#PasswordAuthentication yes'
      line: 'PasswordAuthentication no'

  - name: Reload sshd service
    service:
      name: sshd
      state: reloaded
